[build]
  command = "python -m pip install -r requirements.txt && python manage.py collectstatic --noinput"
  publish = "staticfiles"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/handler"
  status = 200
  force = true

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
